add `fmc_smart_license`
netascode/terraform-provider-fmc pull request #161
Opened 2024-10-30 15:13 UTC by igiai

2024-11-08 13:37 UTC, rchrabas requested changes

2024-11-12 13:15 UTC, igiai commented on main.go
> +
Sure, I'll make a separate PR for debug configs

2024-11-12 13:16 UTC, igiai commented on internal/provider/resource_fmc_smart_license_test.go
> +}
I noticed I need to fix tests anyway. This line will change

2024-12-02 10:53 UTC, danischm requested changes

2024-12-02 10:53 UTC, danischm commented on gen/definitions/smart_license.yaml
> +  - model_name: regStatus
Should this be a read-only/computed attribute or can this be set somehow?

2025-01-28 20:39 UTC, rchrabas commented
Moved work to local branch

2025-01-28 20:39 UTC, closed without merging