add `fmc_icmpv4_object`
netascode/terraform-provider-fmc pull request #74
Opened 2024-07-10 16:40 UTC by jabielecki

Closes #42

No manual code.

2024-07-10 19:48 UTC, danischm requested changes

2024-07-10 19:48 UTC, danischm commented on gen/definitions/icmpv4_object.yaml
> +name: Icmpv4 Object
`name: ICMPv4 Object`

2024-07-10 19:48 UTC, danischm commented on gen/definitions/icmpv4_object.yaml
> +skip_minimum_test: true
Is there a specific reason for this?

2024-07-10 20:05 UTC, jabielecki commented on gen/definitions/icmpv4_object.yaml
> +skip_minimum_test: true
done, thanks

2024-07-10 20:05 UTC, jabielecki commented on gen/definitions/icmpv4_object.yaml
> +name: Icmpv4 Object
done, thanks!

2024-07-11 13:57 UTC, danischm approved these changes

2024-07-11 13:57 UTC, merged